name: "Build Docker Image"

on:
  push:
    branches:
    - master
  release:
    types: [published]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Publish to Registry"
        uses: docker/build-push-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          repository: bschmidt135/zerorpc-ml-model-deployment
          tags: latest